import type { Metadata } from "next";
import { Montserrat, Poppins, DM_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/project/Header";
import Hero from "@/components/project/Hero";
import Countdown from "@/components/project/Countdown";
import AboutEvent from "@/components/project/About";
import Schedule from "@/components/project/Schedule";
import Partners from "@/components/project/Partners";
import Footer from "@/components/project/Footer";
import Faq from "@/components/project/Faq";
import Location from "@/components/project/Location";
import Subscription from "@/components/project/Subscription";
import News from "@/components/project/News";
import { ScrollToTop } from "@/components/ui/scroll-to-top";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins", 
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900", "1000"],
  display: "swap",
});

export const metadata: Metadata = { 
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${montserrat.variable} ${poppins.variable} ${dmSans.variable} antialiased`}
      >
        <Header /> 
        <div className="pt-0">
          <Hero/>
          {/* <Countdown/> */}
          <AboutEvent/>
          <Schedule/>
          <Partners/>
          
          <main>{children}</main>
          <News/>

          <Faq/>
          <Location/>
          <ScrollToTop/>
        </div>
        <Footer/>
      </body>
    </html>
  );
}
