import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/project/Header";
import Hero from "@/components/project/Hero";
import Countdown from "@/components/project/Countdown";
import AboutEvent from "@/components/project/About";
import Schedule from "@/components/project/Schedule";
import Partners from "@/components/project/Partners";
import Footer from "@/components/project/Footer";
import Faq from "@/components/project/Faq";
import Location from "@/components/project/Location";
import Subscription from "@/components/project/Subscription";
import News from "@/components/project/News";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins", 
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = { 
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${montserrat.variable} ${poppins.variable} antialiased`}
      >
        <div className="min-h-screen flex flex-col">
          <Header /> 
          
          <main className="flex-1">
            <Hero/>
            {/* <Countdown/> */}
            <AboutEvent/>
            <Schedule/>
            <Subscription/>
            <Partners/>
            
            <div className="container mx-auto px-4 sm:px-6 lg:px-8">
              {children}
            </div>
            
            <News/>
            <Faq/>
            <Location/>
          </main>
          
          <Footer/>
        </div>
      </body>
    </html>
  );
}
