/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    speakers: Speaker;
    partners: Partner;
    editions: Edition;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    editions: EditionsSelect<false> | EditionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Gerencie os usuários com permissão de acesso e edição no painel administrativo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Nome do administrador
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Gerencie e faça upload de imagens, logotipos, banners e fotos para uso em qualquer edição do site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descrição acessível da imagem para leitores de tela e indexação no Google.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Banco global de palestrantes, oficineiros, pesquisadores e convidados.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  /**
   * Ex: Dra. Maria Silva
   */
  name: string;
  /**
   * Ex: Especialista em IA / Professora Doutora
   */
  role?: string | null;
  /**
   * Ex: UNITINS / MCTI / Google
   */
  institution?: string | null;
  /**
   * URL para o perfil acadêmico ou rede social
   */
  link?: string | null;
  /**
   * Foto do palestrante para exibição nos cards da programação.
   */
  photo?: (number | null) | Media;
  /**
   * Breve histórico profissional e acadêmico do palestrante.
   */
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Cadastro global de instituições parceiras, órgãos de fomento, apoiadores e patrocinadores do evento.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * Ex: MCTI, Governo do Estado do Tocantins, Sebrae
   */
  name: string;
  /**
   * Define a ordem e o agrupamento visual no grid de parceiros.
   */
  category: 'realizacao' | 'correalizacao' | 'patrocinio-master' | 'patrocinio' | 'apoio-institucional' | 'apoio';
  /**
   * Faça upload da imagem da logo com fundo transparente (PNG ou SVG recomendado).
   */
  logo?: (number | null) | Media;
  /**
   * Caminho estático ou link externo alternativo (ex: /logos/logo-snct.png).
   */
  logoUrl?: string | null;
  /**
   * URL de destino ao clicar no logo (ex: https://www.to.gov.br/)
   */
  href?: string | null;
  /**
   * Menor número aparece primeiro no grid (ex: 1, 2, 3...)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gerencie as edições anuais do evento, temas visuais, programação, palestras e parceiros.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editions".
 */
export interface Edition {
  id: number;
  /**
   * Ex: 2025 ou 2026
   */
  year: number;
  /**
   * Caminho na barra de endereços (ex: 2025 para unitinscti.com.br/2025)
   */
  slug: string;
  /**
   * Ao marcar, a rota raiz ( / ) redirecionará automaticamente para esta edição
   */
  isDefault?: boolean | null;
  /**
   * Exibido no topo da página, metadados do Google e compartilhamento em redes sociais
   */
  title: string;
  /**
   * Versão concisa utilizada no cabeçalho e rodapé para economia de espaço
   */
  shortTitle?: string | null;
  /**
   * Exibido nos cards e no cabeçalho (ex: 20 a 24 de outubro de 2025)
   */
  dates?: string | null;
  /**
   * URL de destino ao clicar no botão "Inscreva-se" do Header e do Hero
   */
  registrationUrl?: string | null;
  theme?: {
    /**
     * Cor dos fundos institucionais, cabeçalhos de tabela e botões principais (padrão: #083D77)
     */
    primaryColor?: string | null;
    /**
     * Cor dos badges, palavras em destaque e botões de chamada (padrão: #e2187f)
     */
    accentColor?: string | null;
    /**
     * Substitui a logo padrão exibida no cabeçalho e rodapé (formato recomendado: PNG ou SVG transparente)
     */
    logo?: (number | null) | Media;
    /**
     * Imagem de pré-visualização ao compartilhar o link no WhatsApp, LinkedIn e Twitter (1200x630px)
     */
    heroBanner?: (number | null) | Media;
    /**
     * Imagem de fundo aplicada suavemente na seção Hero do evento
     */
    heroBackground?: (number | null) | Media;
  };
  /**
   * Adicione fotos em alta resolução ou vídeos MP4 curtos para o banner rotativo.
   */
  heroSlides?:
    | {
        type: 'image' | 'video';
        /**
         * Faça upload direto da imagem (com preview visual)
         */
        image?: (number | null) | Media;
        /**
         * Ex: https://videos.pexels.com/... ou https://images.unsplash.com/...
         */
        src?: string | null;
        /**
         * Ex: "Auditório lotado durante a abertura da SCTI"
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  about?: {
    title?: string | null;
    /**
     * Exibido em destaque como o tema norteador das palestras do ano
     */
    themeTitle?: string | null;
    /**
     * Resumo com os objetivos, público-alvo e relevância da edição
     */
    body?: string | null;
    /**
     * Imagem flutuante ao lado do texto da seção Sobre (ex: globo terrestre ou arte temática)
     */
    illustration?: (number | null) | Media;
  };
  /**
   * Organize os dias do evento. Dentro de cada dia, cadastre os eixos temáticos (sub-eventos) e suas respectivas palestras e atividades.
   */
  schedule?:
    | {
        /**
         * Ex: 20/10 ou 20 a 24/10
         */
        date: string;
        /**
         * Ex: Segunda-feira ou Todos os dias
         */
        dayOfWeek: string;
        /**
         * Ex: "Encontro Estadual das Licenciaturas", "XXXII Jornada de Iniciação Científica", "III SCTI", "Embrapa", etc.
         */
        events?:
          | {
              /**
               * Ex: "Encontro Estadual das Licenciaturas da Unitins", "III SCTI", "III Circuito de Inovação"
               */
              name: string;
              talks?:
                | {
                    titulo: string;
                    /**
                     * Ex: 8h30 - 11h ou 14h - 17h
                     */
                    horario: string;
                    /**
                     * Ex: Auditório Planeta Água ou Sala 4 - Bloco B
                     */
                    local: string;
                    /**
                     * Ex: Arthur Igreja ou Prof.ª Dr.ª Raquel Aparecida Marra
                     */
                    palestrante?: string | null;
                    /**
                     * Conecta ao perfil detalhado com foto e biografia
                     */
                    speakerRef?: (number | null) | Speaker;
                    /**
                     * Ex: 120 ou 60
                     */
                    vagas?: string | null;
                    /**
                     * Ex: https://meet.google.com/... ou YouTube
                     */
                    meetLink?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Escolha os parceiros cadastrados na coleção global de Parceiros para exibi-los nesta edição.
   */
  partners?: (number | Partner)[] | null;
  faqs?:
    | {
        /**
         * Ex: "Como recebo o certificado de participação?"
         */
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  subscription?: {
    title?: string | null;
    ctaLabel?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'editions';
        value: number | Edition;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  institution?: T;
  link?: T;
  photo?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  logo?: T;
  logoUrl?: T;
  href?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "editions_select".
 */
export interface EditionsSelect<T extends boolean = true> {
  year?: T;
  slug?: T;
  isDefault?: T;
  title?: T;
  shortTitle?: T;
  dates?: T;
  registrationUrl?: T;
  theme?:
    | T
    | {
        primaryColor?: T;
        accentColor?: T;
        logo?: T;
        heroBanner?: T;
        heroBackground?: T;
      };
  heroSlides?:
    | T
    | {
        type?: T;
        image?: T;
        src?: T;
        alt?: T;
        id?: T;
      };
  about?:
    | T
    | {
        title?: T;
        themeTitle?: T;
        body?: T;
        illustration?: T;
      };
  schedule?:
    | T
    | {
        date?: T;
        dayOfWeek?: T;
        events?:
          | T
          | {
              name?: T;
              talks?:
                | T
                | {
                    titulo?: T;
                    horario?: T;
                    local?: T;
                    palestrante?: T;
                    speakerRef?: T;
                    vagas?: T;
                    meetLink?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  partners?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  subscription?:
    | T
    | {
        title?: T;
        ctaLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}